# Generated by Django 5.1.4 on 2025-01-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_created_by_alter_assignment_course'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
    ]
