name: Django Tests

on:
  push:
    branches:
      - add-ci-backend-frontend  # Adjust this if needed
  pull_request:
    branches:
      - add-ci-backend-frontend  # Adjust this if needed

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the runner for the job

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: django_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # Checkout the code to the GitHub runner
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust Python version as needed

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run database migrations (adjust working directory if needed)
    - name: Run migrations
      working-directory: myapp/myproject  # Ensure this points to the correct directory
      run: |
        python manage.py migrate

    # Run tests (adjust working directory if needed)
    - name: Run tests
      working-directory: myapp/myproject  # Ensure this points to the correct directory
      run: |
        python manage.py test
