test-frontend:
    runs-on: ubuntu-latest  # Use Ubuntu because npm/yarn works best here
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Make sure your project requires Node 16 or change accordingly

      - name: Install dependencies
        run: |
          npm install  # Or you can use 'yarn install' if your project uses yarn instead of npm

      - name: Run frontend tests
        run: |
          npm test  # Or run other npm scripts (e.g., 'yarn test')
