name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version used by your project

    - name: Install dependencies
      run: |
        npm install  # Or 'yarn install' if you're using Yarn

    - name: Run frontend tests
      run: |
        npm test  # Adjust this to your preferred test command (e.g., `yarn test`, `react-scripts test`, etc.)
